### ISSUE TITLE
[defscreen] Pass unrecognized forms through to the configured app component as props

### ISSUE THREAD

**Issue by yanivtal** [functionalfoundry/macros#27]

**Comment by Jannis** [comment]
This only applies to `(navigation ...)`, I assume? The layout fields are preprocessed by translating them each of them into a component factory and props resulting from the component's query.

Or do we want to support other forms in addition to `navigation` and `layout` that we want to pass down untouched?

**Comment by Jannis** [comment]
This is supported since https://github.com/workfloapp/macros/commit/93d0f33ceed8ea2dcbccd2535f569bba91594cd1 and https://github.com/workfloapp/macros/commit/8bff1a0a11c494698e4755cf0a45328903cdb6df.
